### ISSUE TITLE
Incorrect log config entry selection

### ISSUE THREAD

**Issue by Toparvion** [Toparvion/analog#12]
Sometimes AnaLog may show composite log that is different from the actually chosen one. For instance, if two separate log config entries are described as:
```yaml
# one
  - group: ARYA
    pathBase: /pub/home/upc/applications/upc2arya/src/projects/
    compositeLogs:
      - node: north
        path: webfront-api/logs01/webfront-api-all.log
        timestamp: yy.MM.dd HH:mm:ss.SSS
# another
  - group: SNOW
    pathBase: /pub/home/upc/applications/upc2snow/src/projects/
    compositeLogs:
      - node: north
        path: webfront-api/logs01/webfront-api-all.log
        timestamp: yy.MM.dd HH:mm:ss.SSS
```
then the first one can be chosen instead of second. 

**The reason** is unsufficient data for calculating `uid` value. At the moment, it [takes](https://github.com/Toparvion/analog/blob/d38004a1e8a05904e162c6dde588caceb8ae6f91/src/main/java/tech/toparvion/analog/model/config/LogConfigEntry.java#L101) 6 parameters: `path, node, title, selected, timestamp, includes`, where `path` is the entry's own path only, not including group's `pathBase`. As a result, two different log config entries may evaluate to the same `uid` if the only difference between them is in the `pathBase`.
